name: Java TestNG Demo CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-test-report:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: java-testng-demo
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build with Maven
        run: mvn clean test
        continue-on-error: true
      - name: Run TestNG Report Action
        uses: anoopgarlapati/action-testng-report@main
        with:
          summary_report: 'true'
          detailed_report: 'true'
          fail_if_empty: 'true'
